import {
  BsGrid,
  BsBarChart,
  BsSliders,
  BsJournalPlus,
  BsLaptop,
  BsCalendarCheck,
  BsPersonCheck,
  BsClipboard,
  BsCashStack,
  BsPersonBadge,
  BsGear,
} from "react-icons/bs";

export const AdminNavOptions = [
  {
    id: "001",
    icon: <BsGrid />,
    url: "/",
    label: "Dashboard",
    span: "Your Activities ",
  },
  {
    id: "002",
    icon: <BsBarChart />,
    url: "/overview",
    label: "Overview",
    span: "View Reports and Status",
  },
  {
    id: "003",
    icon: <BsSliders />,
    url: "/modules",
    label: "Modules",
    span: "",
  },
  {
    id: "004",
    icon: <BsJournalPlus />,
    url: "/registration",
    label: "Registration",
    span: "Add/Remove/Modify Documents",
  },
  {
    id: "005",
    icon: <BsLaptop />,
    url: "/courses",
    label: "Courses",
    span: "",
  },
  {
    id: "006",
    icon: <BsCashStack />,
    url: "/finance",
    label: "Finance",
    span: "Payment and Invoice Records",
  },
  {
    id: "007",
    icon: <BsPersonBadge />,
    url: "/profile",
    label: "Profile",
    span: "Manage your Profile",
  },
  {
    id: "008",
    icon: <BsGear />,
    url: "/settings",
    label: "Settings",
    span: "",
  },
];
export const StaffNavOptions = [
  {
    id: "011",
    icon: <BsGrid />,
    url: "/",
    label: "Dashboard",
    span: "Your Activities ",
  },
  {
    id: "012",
    icon: <BsPersonCheck />,
    url: "/attendance",
    label: "Attendance",
    span: "",
  },
  {
    id: "013",
    icon: <BsCalendarCheck />,
    url: "/time-table",
    label: "Timetable",
    span: "",
  },
  {
    id: "014",
    icon: <BsLaptop />,
    url: "/courses",
    label: "Courses",
    span: "",
  },
  {
    id: "015",
    icon: <BsBarChart />,
    url: "/overview",
    label: "Overview",
    span: "View Reports and Status",
  },
  {
    id: "016",
    icon: <BsClipboard />,
    url: "/questions",
    label: "Questions",
    span: "",
  },
  {
    id: "017",
    icon: <BsCashStack />,
    url: "/finance",
    label: "Finance",
    span: "Payment and Invoice Records",
  },
  {
    id: "018",
    icon: <BsPersonBadge />,
    url: "/profile",
    label: "Profile",
    span: "Manage your Profile",
  },
  {
    id: "019",
    icon: <BsGear />,
    url: "/settings",
    label: "Settings",
    span: "",
  },
];

export const StudentNavOptions = [
  {
    id: "021",
    icon: <BsGrid />,
    url: "/",
    label: "Dashboard",
    span: "Your Activities ",
  },
  {
    id: "022",
    icon: <BsCalendarCheck />,
    url: "/time-table",
    label: "Timetable",
    span: "",
  },
  {
    id: "023",
    icon: <BsLaptop />,
    url: "/courses",
    label: "Courses",
    span: "",
  },
  {
    id: "024",
    icon: <BsBarChart />,
    url: "/overview",
    label: "Overview",
    span: "View Reports and Status",
  },
  {
    id: "006",
    icon: <BsCashStack />,
    url: "/finance",
    label: "Finance",
    span: "Payment and invoice records",
  },
  {
    id: "007",
    icon: <BsPersonBadge />,
    url: "/profile",
    label: "Profile",
    span: "Manage youI ProfilR",
  },
  {
    id: "008",
    icon: <BsGear />,
    url: "/settings",
    label: "Settings",
    span: "",
  },
];
